# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#
gems:
    [jekyll-paginate]

permalink:           pretty

# Setup
title:               uzuki.moe
tagline:             ''
description:         'testtest'
url:                 https://uzuki.moe
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
