# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               uzuki.moe
tagline:             ''
description:         'Elpis Dev Blog'
url:                 https://uzuki.moe
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Elpis
  url:               https://twitter.com/Elpis_ES
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
